# Generated by Django 4.1 on 2022-08-26 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_food', models.CharField(max_length=30)),
                ('price_food', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image_food', models.ImageField(upload_to='')),
                ('food_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_user', models.CharField(max_length=11)),
                ('name_user', models.CharField(max_length=30)),
                ('birthDate_user', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password_user', models.CharField(max_length=20)),
                ('password2_user', models.CharField(max_length=20)),
                ('user_permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('S', 'Solicitado'), ('P', 'Produção'), ('E', 'Entregue')], default='S', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dompizzaioloApp.user')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dompizzaioloApp.food')),
            ],
        ),
    ]
