# Generated by Django 4.1 on 2022-08-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dompizzaioloApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food',
            new_name='name_food',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='name_user',
        ),
    ]
